language: python
python:
  #- "2.7"  # wrong pip used by travis
  #- "3.3"  # matplotlib requires Python 3.4 or later
  #- "3.4"  # scikit-learn requires SciPy >= 0.9, SciPy 0.9 requires Python >= 3.5
  - "3.5"
  - "3.6"
  - "nightly"
install: "pip install ."
script: pytest
